#include <cmath>
#include <cstdio>
#include <cstdlib>

#include "src/Animation.hpp"
#include "src/Base.hpp"
#include "src/Engine.hpp"
#include "src/Objects.hpp"
#include "src/d3d/rwd3d.h"
#include "src/d3d/rwd3d8.h"
#include "src/d3d/rwd3d9.h"
#include "src/d3d/rwxbox.h"
#include "src/gl/rwgl3.h"
#include "src/gl/rwgl3shader.h"
#include "src/gl/rwwdgl.h"
#include "src/ps2/rwps2.h"
#include "src/ps2/rwps2plg.h"
#include "src/Error.hpp"
#include "src/Pipeline.hpp"
#include "src/Plg.hpp"
#include "src/rwplugins.h"
#include "src/Render.hpp"
#include "src/UserData.hpp"
